name: test

on: [ push ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.3
        with:
          ref: ${{ github.ref }}
      - uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Build tests
        uses: burrunan/gradle-cache-action@v1
        with:
          job-id: jdk11
          arguments: :test:check